### ISSUE TITLE
Port steam-crypto

### ISSUE THREAD

**Issue by saskenuba** [saskenuba/SteamHelper-rs#1]
In order to properly code/decode steam messages (client, web API, etc) we need to fully port steam-crypto.

We can base our implementation on similar projects such as [SteamKit/Crypto Helper files](https://github.com/SteamRE/SteamKit/blob/master/SteamKit2/SteamKit2/Util/CryptoHelper.cs) and [DoctorMckay/node-steam-crypto](https://github.com/DoctorMcKay/node-steam-crypto/blob/master/index.js).

This should not be too difficult, but there has to be some sensible checking because there are lots of details.

**Comment by Leorii** [comment]
Hey! Would you like help with this issue, or should I start on #2 ?

**Comment by saskenuba** [comment]
You can start directly on issue #2. There is also a need to think about how
the general API would work. In the sense of the workflow of logging in,
react to events and do actions.
