### ISSUE TITLE
Discord invite in README has expired

### ISSUE THREAD

**Issue by fyrak1s** [saskenuba/SteamHelper-rs#6]
The Discord invitation link in `SteamHelper-rs/docs/dev/README.md` has expired.

The new link should probably be created with the "Set this link to never expire" option :smile:

**Comment by saskenuba** [comment]
Thanks for the heads up, already went and fixed the docs. The new invitation link is the following: https://discord.gg/s2YRVPy

Sorry for a long time without a reply, I was on vacations, progress should resume.
