### ISSUE TITLE
Upgrade `enum_dispatch` crate to the latest version

### ISSUE THREAD

**Issue by OutOfBears** [saskenuba/SteamHelper-rs#7]
In the version of the `enum_dispatch` crate, it seems to use some API that is not public, and breaks. The author of the crate has since changed the package to not use such API. [See issue here](https://gitlab.com/antonok/enum_dispatch/-/issues/37)

**Comment by saskenuba** [comment]
8095664a56df33723b18612a39e28af149c19874 should fix this. Thanks!
