### ISSUE TITLE
steam-protobuf: Outdated generated protobuf

### ISSUE THREAD

**Issue by OutOfBears** [saskenuba/SteamHelper-rs#8]
After messing around and trying to make the library compile, it would seem that the currently generated protobuf is outdated, along with a new folder that is passed to `protoc`, causing steam-protobuf to fail its generation.

**Comment by saskenuba** [comment]
I think 094dbdccc8dc5a4ba9cc9c29221b99da3124edf8 fixed this. Can you check if it builds now?

**Comment by OutOfBears** [comment]
Yeah, after checking this bug no longer occurs. Thanks for the fix! 👌
